Hotfix/4.4.0 py version fix
CompuCell3D/cc3d-player5 pull request #26
Opened 2023-04-29 23:51 UTC by maciekswat

Fixing code to work with python 3.9 and recent numpy versions

2023-06-14 12:31 UTC, tjsego requested changes
Minor cleanup here. Otherwise, looks great.

2023-06-26 21:04 UTC, tjsego requested changes
Looks good. Just needs previously raised issues resolved.

2023-07-01 18:04 UTC, maciekswat commented on conda-recipes/versions.yaml
> +version: 4.5.0
Fixed

2023-07-01 18:04 UTC, maciekswat commented on VERSION.txt
> +4.5.0
Fixed

2023-07-01 18:04 UTC, maciekswat commented on conda-recipes/versions.yaml
> +version: 4.4.1
Fixed

2023-07-02 00:54 UTC, tjsego approved these changes

2023-07-04 16:18 UTC, merged